package com.messaggi.domain;

// Generated Oct 8, 2013 1:37:50 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * ApplicationPlatformMsgLog generated by hbm2java
 */
public class ApplicationPlatformMsgLog implements java.io.Serializable
{

    private long id;

    private ApplicationPlatform applicationPlatform;

    private Date date;

    private int msgCount;

    public ApplicationPlatformMsgLog()
    {
    }

    public ApplicationPlatformMsgLog(long id, ApplicationPlatform applicationPlatform, Date date, int msgCount)
    {
        this.id = id;
        this.applicationPlatform = applicationPlatform;
        this.date = date;
        this.msgCount = msgCount;
    }

    public long getId()
    {
        return this.id;
    }

    public void setId(long id)
    {
        this.id = id;
    }

    public ApplicationPlatform getApplicationPlatform()
    {
        return this.applicationPlatform;
    }

    public void setApplicationPlatform(ApplicationPlatform applicationPlatform)
    {
        this.applicationPlatform = applicationPlatform;
    }

    public Date getDate()
    {
        return this.date;
    }

    public void setDate(Date date)
    {
        this.date = date;
    }

    public int getMsgCount()
    {
        return this.msgCount;
    }

    public void setMsgCount(int msgCount)
    {
        this.msgCount = msgCount;
    }

}
