package com.messaggi.domain;

// Generated Oct 11, 2013 3:07:40 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ApplicationPlatformMsgLog generated by hbm2java
 */
@Entity
@Table(name = "application_platform_msg_log", schema = "public")
public class ApplicationPlatformMsgLog implements java.io.Serializable
{

    private long id;

    private ApplicationPlatform applicationPlatform;

    private Date date;

    private int msgCount;

    public ApplicationPlatformMsgLog()
    {
    }

    public ApplicationPlatformMsgLog(long id, ApplicationPlatform applicationPlatform, Date date, int msgCount)
    {
        this.id = id;
        this.applicationPlatform = applicationPlatform;
        this.date = date;
        this.msgCount = msgCount;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    public long getId()
    {
        return this.id;
    }

    public void setId(long id)
    {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "application_platform_id", nullable = false)
    public ApplicationPlatform getApplicationPlatform()
    {
        return this.applicationPlatform;
    }

    public void setApplicationPlatform(ApplicationPlatform applicationPlatform)
    {
        this.applicationPlatform = applicationPlatform;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "date", nullable = false, length = 29)
    public Date getDate()
    {
        return this.date;
    }

    public void setDate(Date date)
    {
        this.date = date;
    }

    @Column(name = "msg_count", nullable = false)
    public int getMsgCount()
    {
        return this.msgCount;
    }

    public void setMsgCount(int msgCount)
    {
        this.msgCount = msgCount;
    }

}
