package com.messaggi.domain;

// Generated Oct 8, 2013 1:37:50 PM by Hibernate Tools 4.0.0

/**
 * ApplicationPlatformDeviceId generated by hbm2java
 */
public class ApplicationPlatformDeviceId implements java.io.Serializable
{

    private long applicationPlatformId;

    private long deviceId;

    public ApplicationPlatformDeviceId()
    {
    }

    public ApplicationPlatformDeviceId(long applicationPlatformId, long deviceId)
    {
        this.applicationPlatformId = applicationPlatformId;
        this.deviceId = deviceId;
    }

    public long getApplicationPlatformId()
    {
        return this.applicationPlatformId;
    }

    public void setApplicationPlatformId(long applicationPlatformId)
    {
        this.applicationPlatformId = applicationPlatformId;
    }

    public long getDeviceId()
    {
        return this.deviceId;
    }

    public void setDeviceId(long deviceId)
    {
        this.deviceId = deviceId;
    }

    public boolean equals(Object other)
    {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof ApplicationPlatformDeviceId))
            return false;
        ApplicationPlatformDeviceId castOther = (ApplicationPlatformDeviceId) other;

        return (this.getApplicationPlatformId() == castOther.getApplicationPlatformId()) &&
                (this.getDeviceId() == castOther.getDeviceId());
    }

    public int hashCode()
    {
        int result = 17;

        result = 37 * result + (int) this.getApplicationPlatformId();
        result = 37 * result + (int) this.getDeviceId();
        return result;
    }

}
