package com.messaggi.domain;

// Generated Oct 8, 2013 1:37:50 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * ApplicationPlatformKey generated by hbm2java
 */
public class ApplicationPlatformKey implements java.io.Serializable
{

    private String key;

    private String description;

    private Set<ApplicationPlatformAttribute> applicationPlatformAttributes = new HashSet<ApplicationPlatformAttribute>(
            0);

    public ApplicationPlatformKey()
    {
    }

    public ApplicationPlatformKey(String key, String description)
    {
        this.key = key;
        this.description = description;
    }

    public ApplicationPlatformKey(String key, String description,
            Set<ApplicationPlatformAttribute> applicationPlatformAttributes)
    {
        this.key = key;
        this.description = description;
        this.applicationPlatformAttributes = applicationPlatformAttributes;
    }

    public String getKey()
    {
        return this.key;
    }

    public void setKey(String key)
    {
        this.key = key;
    }

    public String getDescription()
    {
        return this.description;
    }

    public void setDescription(String description)
    {
        this.description = description;
    }

    public Set<ApplicationPlatformAttribute> getApplicationPlatformAttributes()
    {
        return this.applicationPlatformAttributes;
    }

    public void setApplicationPlatformAttributes(Set<ApplicationPlatformAttribute> applicationPlatformAttributes)
    {
        this.applicationPlatformAttributes = applicationPlatformAttributes;
    }

}
