package com.messaggi.domain;

// Generated Oct 7, 2013 3:42:44 PM by Hibernate Tools 4.0.0

/**
 * ApplicationPlatformAttributeId generated by hbm2java
 */
public class ApplicationPlatformAttributeId implements java.io.Serializable
{

    private ApplicationPlatform applicationPlatform;

    private ApplicationPlatformKey applicationPlatformKey;

    public ApplicationPlatformAttributeId()
    {
    }

    public ApplicationPlatformAttributeId(ApplicationPlatform applicationPlatform,
            ApplicationPlatformKey applicationPlatformKey)
    {
        this.applicationPlatform = applicationPlatform;
        this.applicationPlatformKey = applicationPlatformKey;
    }

    public ApplicationPlatform getApplicationPlatform()
    {
        return this.applicationPlatform;
    }

    public void setApplicationPlatform(ApplicationPlatform applicationPlatform)
    {
        this.applicationPlatform = applicationPlatform;
    }

    public ApplicationPlatformKey getApplicationPlatformKey()
    {
        return this.applicationPlatformKey;
    }

    public void setApplicationPlatformKey(ApplicationPlatformKey applicationPlatformKey)
    {
        this.applicationPlatformKey = applicationPlatformKey;
    }

    public boolean equals(Object other)
    {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof ApplicationPlatformAttributeId))
            return false;
        ApplicationPlatformAttributeId castOther = (ApplicationPlatformAttributeId) other;

        return ((this.getApplicationPlatform() == castOther.getApplicationPlatform()) || (this.getApplicationPlatform() != null &&
                castOther.getApplicationPlatform() != null && this.getApplicationPlatform().equals(
                castOther.getApplicationPlatform()))) &&
                ((this.getApplicationPlatformKey() == castOther.getApplicationPlatformKey()) || (this
                        .getApplicationPlatformKey() != null && castOther.getApplicationPlatformKey() != null && this
                        .getApplicationPlatformKey().equals(castOther.getApplicationPlatformKey())));
    }

    public int hashCode()
    {
        int result = 17;

        result = 37 * result + (getApplicationPlatform() == null ? 0 : this.getApplicationPlatform().hashCode());
        result = 37 * result + (getApplicationPlatformKey() == null ? 0 : this.getApplicationPlatformKey().hashCode());
        return result;
    }

}
