package com.messaggi.domain;

// Generated Oct 7, 2013 3:42:44 PM by Hibernate Tools 4.0.0

/**
 * DeviceAttribute generated by hbm2java
 */
public class DeviceAttribute implements java.io.Serializable
{

    private DeviceAttributeId id;

    private String value;

    public DeviceAttribute()
    {
    }

    public DeviceAttribute(DeviceAttributeId id, String value)
    {
        this.id = id;
        this.value = value;
    }

    public DeviceAttributeId getId()
    {
        return this.id;
    }

    public void setId(DeviceAttributeId id)
    {
        this.id = id;
    }

    public String getValue()
    {
        return this.value;
    }

    public void setValue(String value)
    {
        this.value = value;
    }

}
