package com.messaggi.domain;

// Generated Oct 7, 2013 12:12:42 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Platform generated by hbm2java
 */
public class Platform implements java.io.Serializable
{

    private long id;

    private String name;

    private String serviceName;

    private boolean active;

    private Set<ApplicationPlatform> applicationPlatforms = new HashSet<ApplicationPlatform>(0);

    public Platform()
    {
    }

    public Platform(long id, String name, String serviceName, boolean active)
    {
        this.id = id;
        this.name = name;
        this.serviceName = serviceName;
        this.active = active;
    }

    public Platform(long id, String name, String serviceName, boolean active,
            Set<ApplicationPlatform> applicationPlatforms)
    {
        this.id = id;
        this.name = name;
        this.serviceName = serviceName;
        this.active = active;
        this.applicationPlatforms = applicationPlatforms;
    }

    public long getId()
    {
        return this.id;
    }

    public void setId(long id)
    {
        this.id = id;
    }

    public String getName()
    {
        return this.name;
    }

    public void setName(String name)
    {
        this.name = name;
    }

    public String getServiceName()
    {
        return this.serviceName;
    }

    public void setServiceName(String serviceName)
    {
        this.serviceName = serviceName;
    }

    public boolean isActive()
    {
        return this.active;
    }

    public void setActive(boolean active)
    {
        this.active = active;
    }

    public Set<ApplicationPlatform> getApplicationPlatforms()
    {
        return this.applicationPlatforms;
    }

    public void setApplicationPlatforms(Set<ApplicationPlatform> applicationPlatforms)
    {
        this.applicationPlatforms = applicationPlatforms;
    }

}
