package com.messaggi.domain;

// Generated Oct 8, 2013 1:37:50 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable
{

    private long id;

    private String name;

    private String email;

    private String phone;

    private String phoneParsed;

    private String password;

    private String locale;

    private boolean active;

    private Set<UserApplication> userApplications = new HashSet<UserApplication>(0);

    public User()
    {
    }

    public User(long id, String name, String email, String phone, String phoneParsed, String password, String locale,
            boolean active)
    {
        this.id = id;
        this.name = name;
        this.email = email;
        this.phone = phone;
        this.phoneParsed = phoneParsed;
        this.password = password;
        this.locale = locale;
        this.active = active;
    }

    public User(long id, String name, String email, String phone, String phoneParsed, String password, String locale,
            boolean active, Set<UserApplication> userApplications)
    {
        this.id = id;
        this.name = name;
        this.email = email;
        this.phone = phone;
        this.phoneParsed = phoneParsed;
        this.password = password;
        this.locale = locale;
        this.active = active;
        this.userApplications = userApplications;
    }

    public long getId()
    {
        return this.id;
    }

    public void setId(long id)
    {
        this.id = id;
    }

    public String getName()
    {
        return this.name;
    }

    public void setName(String name)
    {
        this.name = name;
    }

    public String getEmail()
    {
        return this.email;
    }

    public void setEmail(String email)
    {
        this.email = email;
    }

    public String getPhone()
    {
        return this.phone;
    }

    public void setPhone(String phone)
    {
        this.phone = phone;
    }

    public String getPhoneParsed()
    {
        return this.phoneParsed;
    }

    public void setPhoneParsed(String phoneParsed)
    {
        this.phoneParsed = phoneParsed;
    }

    public String getPassword()
    {
        return this.password;
    }

    public void setPassword(String password)
    {
        this.password = password;
    }

    public String getLocale()
    {
        return this.locale;
    }

    public void setLocale(String locale)
    {
        this.locale = locale;
    }

    public boolean isActive()
    {
        return this.active;
    }

    public void setActive(boolean active)
    {
        this.active = active;
    }

    public Set<UserApplication> getUserApplications()
    {
        return this.userApplications;
    }

    public void setUserApplications(Set<UserApplication> userApplications)
    {
        this.userApplications = userApplications;
    }

}
