package com.messaggi.domain;

// Generated Oct 2, 2013 11:12:51 AM by Hibernate Tools 4.0.0

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * ApplicationPlatform generated by hbm2java
 */
public class ApplicationPlatform implements java.io.Serializable
{

    private long id;

    private Platform platform;

    private Application application;

    private Serializable token;

    private Set<ApplicationPlatformMsgLog> applicationPlatformMsgLogs = new HashSet<ApplicationPlatformMsgLog>(0);

    private Set<ApplicationPlatformAttribute> applicationPlatformAttributes = new HashSet<ApplicationPlatformAttribute>(
            0);

    public ApplicationPlatform()
    {
    }

    public ApplicationPlatform(long id, Platform platform, Application application, Serializable token)
    {
        this.id = id;
        this.platform = platform;
        this.application = application;
        this.token = token;
    }

    public ApplicationPlatform(long id, Platform platform, Application application, Serializable token,
            Set<ApplicationPlatformMsgLog> applicationPlatformMsgLogs,
            Set<ApplicationPlatformAttribute> applicationPlatformAttributes)
    {
        this.id = id;
        this.platform = platform;
        this.application = application;
        this.token = token;
        this.applicationPlatformMsgLogs = applicationPlatformMsgLogs;
        this.applicationPlatformAttributes = applicationPlatformAttributes;
    }

    public long getId()
    {
        return this.id;
    }

    public void setId(long id)
    {
        this.id = id;
    }

    public Platform getPlatform()
    {
        return this.platform;
    }

    public void setPlatform(Platform platform)
    {
        this.platform = platform;
    }

    public Application getApplication()
    {
        return this.application;
    }

    public void setApplication(Application application)
    {
        this.application = application;
    }

    public Serializable getToken()
    {
        return this.token;
    }

    public void setToken(Serializable token)
    {
        this.token = token;
    }

    public Set<ApplicationPlatformMsgLog> getApplicationPlatformMsgLogs()
    {
        return this.applicationPlatformMsgLogs;
    }

    public void setApplicationPlatformMsgLogs(Set<ApplicationPlatformMsgLog> applicationPlatformMsgLogs)
    {
        this.applicationPlatformMsgLogs = applicationPlatformMsgLogs;
    }

    public Set<ApplicationPlatformAttribute> getApplicationPlatformAttributes()
    {
        return this.applicationPlatformAttributes;
    }

    public void setApplicationPlatformAttributes(Set<ApplicationPlatformAttribute> applicationPlatformAttributes)
    {
        this.applicationPlatformAttributes = applicationPlatformAttributes;
    }

}
