package com.messaggi.domain;

// Generated Oct 2, 2013 11:12:51 AM by Hibernate Tools 4.0.0

/**
 * ApplicationPlatformAttribute generated by hbm2java
 */
public class ApplicationPlatformAttribute implements java.io.Serializable
{

    private ApplicationPlatformAttributeId id;

    private String value;

    public ApplicationPlatformAttribute()
    {
    }

    public ApplicationPlatformAttribute(ApplicationPlatformAttributeId id, String value)
    {
        this.id = id;
        this.value = value;
    }

    public ApplicationPlatformAttributeId getId()
    {
        return this.id;
    }

    public void setId(ApplicationPlatformAttributeId id)
    {
        this.id = id;
    }

    public String getValue()
    {
        return this.value;
    }

    public void setValue(String value)
    {
        this.value = value;
    }

}
