package com.messaggi.domain;

// Generated Oct 11, 2013 3:07:40 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import java.util.UUID;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ApplicationPlatform generated by hbm2java
 */
@Entity
@Table(name = "application_platform", schema = "public")
public class ApplicationPlatform implements java.io.Serializable
{

    private long id;

    private Platform platform;

    private Application application;

    private UUID token;

    private Set<ApplicationPlatformMsgLog> applicationPlatformMsgLogs = new HashSet<ApplicationPlatformMsgLog>(0);

    private Set<ApplicationPlatformAttribute> applicationPlatformAttributes = new HashSet<ApplicationPlatformAttribute>(
            0);

    public ApplicationPlatform()
    {
    }

    public ApplicationPlatform(long id, Platform platform, Application application, UUID token)
    {
        this.id = id;
        this.platform = platform;
        this.application = application;
        this.token = token;
    }

    public ApplicationPlatform(long id, Platform platform, Application application, UUID token,
            Set<ApplicationPlatformMsgLog> applicationPlatformMsgLogs,
            Set<ApplicationPlatformAttribute> applicationPlatformAttributes)
    {
        this.id = id;
        this.platform = platform;
        this.application = application;
        this.token = token;
        this.applicationPlatformMsgLogs = applicationPlatformMsgLogs;
        this.applicationPlatformAttributes = applicationPlatformAttributes;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    public long getId()
    {
        return this.id;
    }

    public void setId(long id)
    {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "platform_id", nullable = false)
    public Platform getPlatform()
    {
        return this.platform;
    }

    public void setPlatform(Platform platform)
    {
        this.platform = platform;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "application_id", nullable = false)
    public Application getApplication()
    {
        return this.application;
    }

    public void setApplication(Application application)
    {
        this.application = application;
    }

    @Column(name = "token", nullable = false)
    public UUID getToken()
    {
        return this.token;
    }

    public void setToken(UUID token)
    {
        this.token = token;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "applicationPlatform")
    public Set<ApplicationPlatformMsgLog> getApplicationPlatformMsgLogs()
    {
        return this.applicationPlatformMsgLogs;
    }

    public void setApplicationPlatformMsgLogs(Set<ApplicationPlatformMsgLog> applicationPlatformMsgLogs)
    {
        this.applicationPlatformMsgLogs = applicationPlatformMsgLogs;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "applicationPlatform")
    public Set<ApplicationPlatformAttribute> getApplicationPlatformAttributes()
    {
        return this.applicationPlatformAttributes;
    }

    public void setApplicationPlatformAttributes(Set<ApplicationPlatformAttribute> applicationPlatformAttributes)
    {
        this.applicationPlatformAttributes = applicationPlatformAttributes;
    }

}
