package com.messaggi.domain;

// Generated Oct 11, 2013 3:07:40 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DeviceAttributeId generated by hbm2java
 */
@Embeddable
public class DeviceAttributeId implements java.io.Serializable
{

    private long deviceId;

    private String key;

    public DeviceAttributeId()
    {
    }

    public DeviceAttributeId(long deviceId, String key)
    {
        this.deviceId = deviceId;
        this.key = key;
    }

    @Column(name = "device_id", nullable = false)
    public long getDeviceId()
    {
        return this.deviceId;
    }

    public void setDeviceId(long deviceId)
    {
        this.deviceId = deviceId;
    }

    @Column(name = "key", nullable = false, length = 20)
    public String getKey()
    {
        return this.key;
    }

    public void setKey(String key)
    {
        this.key = key;
    }

    public boolean equals(Object other)
    {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof DeviceAttributeId))
            return false;
        DeviceAttributeId castOther = (DeviceAttributeId) other;

        return (this.getDeviceId() == castOther.getDeviceId()) &&
                ((this.getKey() == castOther.getKey()) || (this.getKey() != null && castOther.getKey() != null && this
                        .getKey().equals(castOther.getKey())));
    }

    public int hashCode()
    {
        int result = 17;

        result = 37 * result + (int) this.getDeviceId();
        result = 37 * result + (getKey() == null ? 0 : this.getKey().hashCode());
        return result;
    }

}
