package com.messaggi.domain;

// Generated Oct 2, 2013 11:12:51 AM by Hibernate Tools 4.0.0

/**
 * DeviceAttributeId generated by hbm2java
 */
public class DeviceAttributeId implements java.io.Serializable
{

    private Device device;

    private DeviceKey deviceKey;

    public DeviceAttributeId()
    {
    }

    public DeviceAttributeId(Device device, DeviceKey deviceKey)
    {
        this.device = device;
        this.deviceKey = deviceKey;
    }

    public Device getDevice()
    {
        return this.device;
    }

    public void setDevice(Device device)
    {
        this.device = device;
    }

    public DeviceKey getDeviceKey()
    {
        return this.deviceKey;
    }

    public void setDeviceKey(DeviceKey deviceKey)
    {
        this.deviceKey = deviceKey;
    }

    public boolean equals(Object other)
    {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof DeviceAttributeId))
            return false;
        DeviceAttributeId castOther = (DeviceAttributeId) other;

        return ((this.getDevice() == castOther.getDevice()) || (this.getDevice() != null &&
                castOther.getDevice() != null && this.getDevice().equals(castOther.getDevice()))) &&
                ((this.getDeviceKey() == castOther.getDeviceKey()) || (this.getDeviceKey() != null &&
                        castOther.getDeviceKey() != null && this.getDeviceKey().equals(castOther.getDeviceKey())));
    }

    public int hashCode()
    {
        int result = 17;

        result = 37 * result + (getDevice() == null ? 0 : this.getDevice().hashCode());
        result = 37 * result + (getDeviceKey() == null ? 0 : this.getDeviceKey().hashCode());
        return result;
    }

}
