package com.messaggi.persistence.domain;

// Generated Oct 15, 2013 8:04:55 AM by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ApplicationPlatformAttribute generated by hbm2java
 */
@Entity
@Table(name = "application_platform_attribute", schema = "public")
public class ApplicationPlatformAttribute implements java.io.Serializable
{

    private ApplicationPlatformAttributeId id;

    private ApplicationPlatform applicationPlatform;

    private ApplicationPlatformKey applicationPlatformKey;

    private String value;

    public ApplicationPlatformAttribute()
    {
    }

    public ApplicationPlatformAttribute(ApplicationPlatformAttributeId id, ApplicationPlatform applicationPlatform,
            ApplicationPlatformKey applicationPlatformKey, String value)
    {
        this.id = id;
        this.applicationPlatform = applicationPlatform;
        this.applicationPlatformKey = applicationPlatformKey;
        this.value = value;
    }

    @EmbeddedId
    @AttributeOverrides({
            @AttributeOverride(name = "applicationPlatformId", column = @Column(name = "application_platform_id", nullable = false)),
            @AttributeOverride(name = "key", column = @Column(name = "key", nullable = false, length = 20)) })
    public ApplicationPlatformAttributeId getId()
    {
        return this.id;
    }

    public void setId(ApplicationPlatformAttributeId id)
    {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "application_platform_id", nullable = false, insertable = false, updatable = false)
    public ApplicationPlatform getApplicationPlatform()
    {
        return this.applicationPlatform;
    }

    public void setApplicationPlatform(ApplicationPlatform applicationPlatform)
    {
        this.applicationPlatform = applicationPlatform;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "key", nullable = false, insertable = false, updatable = false)
    public ApplicationPlatformKey getApplicationPlatformKey()
    {
        return this.applicationPlatformKey;
    }

    public void setApplicationPlatformKey(ApplicationPlatformKey applicationPlatformKey)
    {
        this.applicationPlatformKey = applicationPlatformKey;
    }

    @Column(name = "value", nullable = false, length = 1024)
    public String getValue()
    {
        return this.value;
    }

    public void setValue(String value)
    {
        this.value = value;
    }

}
