package com.messaggi.persistence.domain;

// Generated Oct 15, 2013 1:23:14 PM by Hibernate Tools 4.0.0

/**
 * ApplicationPlatformAttribute generated by hbm2java
 */
public class ApplicationPlatformAttribute implements java.io.Serializable
{

    private ApplicationPlatformAttributeId id;

    private ApplicationPlatform applicationPlatform;

    private ApplicationPlatformKey applicationPlatformKey;

    private String value;

    public ApplicationPlatformAttribute()
    {
    }

    public ApplicationPlatformAttribute(ApplicationPlatformAttributeId id, ApplicationPlatform applicationPlatform,
            ApplicationPlatformKey applicationPlatformKey, String value)
    {
        this.id = id;
        this.applicationPlatform = applicationPlatform;
        this.applicationPlatformKey = applicationPlatformKey;
        this.value = value;
    }

    public ApplicationPlatformAttributeId getId()
    {
        return this.id;
    }

    public void setId(ApplicationPlatformAttributeId id)
    {
        this.id = id;
    }

    public ApplicationPlatform getApplicationPlatform()
    {
        return this.applicationPlatform;
    }

    public void setApplicationPlatform(ApplicationPlatform applicationPlatform)
    {
        this.applicationPlatform = applicationPlatform;
    }

    public ApplicationPlatformKey getApplicationPlatformKey()
    {
        return this.applicationPlatformKey;
    }

    public void setApplicationPlatformKey(ApplicationPlatformKey applicationPlatformKey)
    {
        this.applicationPlatformKey = applicationPlatformKey;
    }

    public String getValue()
    {
        return this.value;
    }

    public void setValue(String value)
    {
        this.value = value;
    }

}
