package com.messaggi.persistence.domain;

// Generated Oct 15, 2013 1:23:14 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import java.util.UUID;

/**
 * ApplicationPlatform generated by hbm2java
 */
public class ApplicationPlatform implements java.io.Serializable
{

    private long id;

    private Platform platform;

    private Application application;

    private UUID token;

    private Set<ApplicationPlatformAttribute> applicationPlatformAttributes = new HashSet<ApplicationPlatformAttribute>(
            0);

    private Set<ApplicationPlatformMsgLog> applicationPlatformMsgLogs = new HashSet<ApplicationPlatformMsgLog>(0);

    public ApplicationPlatform()
    {
    }

    public ApplicationPlatform(long id, Platform platform, Application application, UUID token)
    {
        this.id = id;
        this.platform = platform;
        this.application = application;
        this.token = token;
    }

    public ApplicationPlatform(long id, Platform platform, Application application, UUID token,
            Set<ApplicationPlatformAttribute> applicationPlatformAttributes,
            Set<ApplicationPlatformMsgLog> applicationPlatformMsgLogs)
    {
        this.id = id;
        this.platform = platform;
        this.application = application;
        this.token = token;
        this.applicationPlatformAttributes = applicationPlatformAttributes;
        this.applicationPlatformMsgLogs = applicationPlatformMsgLogs;
    }

    public long getId()
    {
        return this.id;
    }

    public void setId(long id)
    {
        this.id = id;
    }

    public Platform getPlatform()
    {
        return this.platform;
    }

    public void setPlatform(Platform platform)
    {
        this.platform = platform;
    }

    public Application getApplication()
    {
        return this.application;
    }

    public void setApplication(Application application)
    {
        this.application = application;
    }

    public UUID getToken()
    {
        return this.token;
    }

    public void setToken(UUID token)
    {
        this.token = token;
    }

    public Set<ApplicationPlatformAttribute> getApplicationPlatformAttributes()
    {
        return this.applicationPlatformAttributes;
    }

    public void setApplicationPlatformAttributes(Set<ApplicationPlatformAttribute> applicationPlatformAttributes)
    {
        this.applicationPlatformAttributes = applicationPlatformAttributes;
    }

    public Set<ApplicationPlatformMsgLog> getApplicationPlatformMsgLogs()
    {
        return this.applicationPlatformMsgLogs;
    }

    public void setApplicationPlatformMsgLogs(Set<ApplicationPlatformMsgLog> applicationPlatformMsgLogs)
    {
        this.applicationPlatformMsgLogs = applicationPlatformMsgLogs;
    }

}
