package com.messaggi.persistence.domain;

// Generated Oct 15, 2013 8:04:55 AM by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ApplicationPlatformDevice generated by hbm2java
 */
@Entity
@Table(name = "application_platform_device", schema = "public")
public class ApplicationPlatformDevice implements java.io.Serializable
{

    private ApplicationPlatformDeviceId id;

    public ApplicationPlatformDevice()
    {
    }

    public ApplicationPlatformDevice(ApplicationPlatformDeviceId id)
    {
        this.id = id;
    }

    @EmbeddedId
    @AttributeOverrides({
            @AttributeOverride(name = "applicationPlatformId", column = @Column(name = "application_platform_id", nullable = false)),
            @AttributeOverride(name = "deviceId", column = @Column(name = "device_id", nullable = false)) })
    public ApplicationPlatformDeviceId getId()
    {
        return this.id;
    }

    public void setId(ApplicationPlatformDeviceId id)
    {
        this.id = id;
    }

}
