package com.messaggi.persistence.domain;

// Generated Oct 15, 2013 8:04:55 AM by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DeviceAttribute generated by hbm2java
 */
@Entity
@Table(name = "device_attribute", schema = "public")
public class DeviceAttribute implements java.io.Serializable
{

    private DeviceAttributeId id;

    private Device device;

    private DeviceKey deviceKey;

    private String value;

    public DeviceAttribute()
    {
    }

    public DeviceAttribute(DeviceAttributeId id, Device device, DeviceKey deviceKey, String value)
    {
        this.id = id;
        this.device = device;
        this.deviceKey = deviceKey;
        this.value = value;
    }

    @EmbeddedId
    @AttributeOverrides({
            @AttributeOverride(name = "deviceId", column = @Column(name = "device_id", nullable = false)),
            @AttributeOverride(name = "key", column = @Column(name = "key", nullable = false, length = 20)) })
    public DeviceAttributeId getId()
    {
        return this.id;
    }

    public void setId(DeviceAttributeId id)
    {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "device_id", nullable = false, insertable = false, updatable = false)
    public Device getDevice()
    {
        return this.device;
    }

    public void setDevice(Device device)
    {
        this.device = device;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "key", nullable = false, insertable = false, updatable = false)
    public DeviceKey getDeviceKey()
    {
        return this.deviceKey;
    }

    public void setDeviceKey(DeviceKey deviceKey)
    {
        this.deviceKey = deviceKey;
    }

    @Column(name = "value", nullable = false, length = 1024)
    public String getValue()
    {
        return this.value;
    }

    public void setValue(String value)
    {
        this.value = value;
    }

}
