package com.messaggi.persistence.domain;

// Generated Oct 15, 2013 8:04:55 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Platform generated by hbm2java
 */
@Entity
@Table(name = "platform", schema = "public")
public class Platform implements java.io.Serializable
{

    private long id;

    private String name;

    private String serviceName;

    private boolean active;

    private Set<ApplicationPlatform> applicationPlatforms = new HashSet<ApplicationPlatform>(0);

    public Platform()
    {
    }

    public Platform(long id, String name, String serviceName, boolean active)
    {
        this.id = id;
        this.name = name;
        this.serviceName = serviceName;
        this.active = active;
    }

    public Platform(long id, String name, String serviceName, boolean active,
            Set<ApplicationPlatform> applicationPlatforms)
    {
        this.id = id;
        this.name = name;
        this.serviceName = serviceName;
        this.active = active;
        this.applicationPlatforms = applicationPlatforms;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    public long getId()
    {
        return this.id;
    }

    public void setId(long id)
    {
        this.id = id;
    }

    @Column(name = "name", nullable = false, length = 100)
    public String getName()
    {
        return this.name;
    }

    public void setName(String name)
    {
        this.name = name;
    }

    @Column(name = "service_name", nullable = false, length = 100)
    public String getServiceName()
    {
        return this.serviceName;
    }

    public void setServiceName(String serviceName)
    {
        this.serviceName = serviceName;
    }

    @Column(name = "active", nullable = false)
    public boolean isActive()
    {
        return this.active;
    }

    public void setActive(boolean active)
    {
        this.active = active;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "platform")
    public Set<ApplicationPlatform> getApplicationPlatforms()
    {
        return this.applicationPlatforms;
    }

    public void setApplicationPlatforms(Set<ApplicationPlatform> applicationPlatforms)
    {
        this.applicationPlatforms = applicationPlatforms;
    }

}
