package com.messaggi.persistence.domain;

// Generated Oct 15, 2013 8:04:55 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", schema = "public")
public class User implements java.io.Serializable
{

    private long id;

    private String name;

    private String email;

    private String phone;

    private String phoneParsed;

    private String password;

    private String locale;

    private boolean active;

    private Set<UserApplication> userApplications = new HashSet<UserApplication>(0);

    public User()
    {
    }

    public User(long id, String name, String email, String phone, String phoneParsed, String password, String locale,
            boolean active)
    {
        this.id = id;
        this.name = name;
        this.email = email;
        this.phone = phone;
        this.phoneParsed = phoneParsed;
        this.password = password;
        this.locale = locale;
        this.active = active;
    }

    public User(long id, String name, String email, String phone, String phoneParsed, String password, String locale,
            boolean active, Set<UserApplication> userApplications)
    {
        this.id = id;
        this.name = name;
        this.email = email;
        this.phone = phone;
        this.phoneParsed = phoneParsed;
        this.password = password;
        this.locale = locale;
        this.active = active;
        this.userApplications = userApplications;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    public long getId()
    {
        return this.id;
    }

    public void setId(long id)
    {
        this.id = id;
    }

    @Column(name = "name", nullable = false, length = 120)
    public String getName()
    {
        return this.name;
    }

    public void setName(String name)
    {
        this.name = name;
    }

    @Column(name = "email", nullable = false, length = 256)
    public String getEmail()
    {
        return this.email;
    }

    public void setEmail(String email)
    {
        this.email = email;
    }

    @Column(name = "phone", nullable = false, length = 50)
    public String getPhone()
    {
        return this.phone;
    }

    public void setPhone(String phone)
    {
        this.phone = phone;
    }

    @Column(name = "phone_parsed", nullable = false, length = 50)
    public String getPhoneParsed()
    {
        return this.phoneParsed;
    }

    public void setPhoneParsed(String phoneParsed)
    {
        this.phoneParsed = phoneParsed;
    }

    @Column(name = "password", nullable = false, length = 512)
    public String getPassword()
    {
        return this.password;
    }

    public void setPassword(String password)
    {
        this.password = password;
    }

    @Column(name = "locale", nullable = false, length = 10)
    public String getLocale()
    {
        return this.locale;
    }

    public void setLocale(String locale)
    {
        this.locale = locale;
    }

    @Column(name = "active", nullable = false)
    public boolean isActive()
    {
        return this.active;
    }

    public void setActive(boolean active)
    {
        this.active = active;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
    public Set<UserApplication> getUserApplications()
    {
        return this.userApplications;
    }

    public void setUserApplications(Set<UserApplication> userApplications)
    {
        this.userApplications = userApplications;
    }

}
