package com.messaggi.persistence.domain;

// Generated Oct 15, 2013 1:23:14 PM by Hibernate Tools 4.0.0

/**
 * ApplicationPlatformDevice generated by hbm2java
 */
public class ApplicationPlatformDevice implements java.io.Serializable
{

    private ApplicationPlatformDeviceId id;

    public ApplicationPlatformDevice()
    {
    }

    public ApplicationPlatformDevice(ApplicationPlatformDeviceId id)
    {
        this.id = id;
    }

    public ApplicationPlatformDeviceId getId()
    {
        return this.id;
    }

    public void setId(ApplicationPlatformDeviceId id)
    {
        this.id = id;
    }

}
