package com.messaggi.persistence.domain;

// Generated Oct 15, 2013 8:04:55 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ApplicationPlatformDeviceId generated by hbm2java
 */
@Embeddable
public class ApplicationPlatformDeviceId implements java.io.Serializable
{

    private long applicationPlatformId;

    private long deviceId;

    public ApplicationPlatformDeviceId()
    {
    }

    public ApplicationPlatformDeviceId(long applicationPlatformId, long deviceId)
    {
        this.applicationPlatformId = applicationPlatformId;
        this.deviceId = deviceId;
    }

    @Column(name = "application_platform_id", nullable = false)
    public long getApplicationPlatformId()
    {
        return this.applicationPlatformId;
    }

    public void setApplicationPlatformId(long applicationPlatformId)
    {
        this.applicationPlatformId = applicationPlatformId;
    }

    @Column(name = "device_id", nullable = false)
    public long getDeviceId()
    {
        return this.deviceId;
    }

    public void setDeviceId(long deviceId)
    {
        this.deviceId = deviceId;
    }

    public boolean equals(Object other)
    {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof ApplicationPlatformDeviceId))
            return false;
        ApplicationPlatformDeviceId castOther = (ApplicationPlatformDeviceId) other;

        return (this.getApplicationPlatformId() == castOther.getApplicationPlatformId()) &&
                (this.getDeviceId() == castOther.getDeviceId());
    }

    public int hashCode()
    {
        int result = 17;

        result = 37 * result + (int) this.getApplicationPlatformId();
        result = 37 * result + (int) this.getDeviceId();
        return result;
    }

}
