package com.messaggi.persistence.domain;

// Generated Oct 15, 2013 1:23:14 PM by Hibernate Tools 4.0.0

/**
 * DeviceAttribute generated by hbm2java
 */
public class DeviceAttribute implements java.io.Serializable
{

    private DeviceAttributeId id;

    private Device device;

    private DeviceKey deviceKey;

    private String value;

    public DeviceAttribute()
    {
    }

    public DeviceAttribute(DeviceAttributeId id, Device device, DeviceKey deviceKey, String value)
    {
        this.id = id;
        this.device = device;
        this.deviceKey = deviceKey;
        this.value = value;
    }

    public DeviceAttributeId getId()
    {
        return this.id;
    }

    public void setId(DeviceAttributeId id)
    {
        this.id = id;
    }

    public Device getDevice()
    {
        return this.device;
    }

    public void setDevice(Device device)
    {
        this.device = device;
    }

    public DeviceKey getDeviceKey()
    {
        return this.deviceKey;
    }

    public void setDeviceKey(DeviceKey deviceKey)
    {
        this.deviceKey = deviceKey;
    }

    public String getValue()
    {
        return this.value;
    }

    public void setValue(String value)
    {
        this.value = value;
    }

}
