package com.messaggi.persistence.domain;

// Generated Oct 15, 2013 1:23:14 PM by Hibernate Tools 4.0.0

/**
 * UserApplication generated by hbm2java
 */
public class UserApplication implements java.io.Serializable
{

    private long applicationId;

    private User user;

    private Application application;

    public UserApplication()
    {
    }

    public UserApplication(User user, Application application)
    {
        this.user = user;
        this.application = application;
    }

    public long getApplicationId()
    {
        return this.applicationId;
    }

    public void setApplicationId(long applicationId)
    {
        this.applicationId = applicationId;
    }

    public User getUser()
    {
        return this.user;
    }

    public void setUser(User user)
    {
        this.user = user;
    }

    public Application getApplication()
    {
        return this.application;
    }

    public void setApplication(Application application)
    {
        this.application = application;
    }

}
